# Dispense volume (uL) [0, 1100]
float64 vol

# Geometry of container table index [0, 99]
int16 gc_idx

# Deck geometry table index [0, 99]
int16 dg_idx

# Liquid class table index [0, 99]
int16 lc_idx

# Container height
float64 container_height

# Height of liquid surface (used only with LLD disabled)
float64 liquid_surface

# Aspirate from top and follow liquid level (0) / from bottom and hold (1)
bool orientation

# Aspiration speed (uL/sec)
float64 speed

---
bool ok
