# Dispense volume (uL) [0, 1100]
float64 vol

# Geometry of container table index [0, 99]
int16 gc_idx

# Deck geometry table index [0, 99]
int16 dg_idx

# Liquid class table index [0, 99]
int16 lc_idx

# QPM [0=off, 1=on]
bool qpm

# Liquid level detection [0=off, 1=on]
bool lld

# LLD search height [0,180]
float64 lld_search_height


# Height of liquid surface (used with LLD disabled)
float64 liquid_surface

# Search bottom mode activated? [0=off, 1=on]
bool search_bottom_mode

# Aspirate from top and follow liquid level (0) / from bottom and hold (1)
bool orientation

# Aspiration speed (uL/sec)
float64 speed

# Tip pre-wetting (true/false)
bool prewet

---
bool ok
